
# .streamlit/config.toml
[theme]
primaryColor = "#2EA39C"              # tvoje zelená
backgroundColor = "#FFFFFF"            # volitelně
secondaryBackgroundColor = "#F5F5F5"   # volitelně
textColor = "#000000"                  # volitelně
font = "sans serif"                    # volitelně
